tim_urfu-teploobmenweb-587e0fcfbe11/TeploobmenWeb/Models/ErrorViewModel.cs
namespace TeploobmenWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

tim_urfu-teploobmenweb-587e0fcfbe11/TeploobmenWeb/Models/HomeViewModel.cs
using TeploobmenWeb.Data;

namespace TeploobmenWeb.Models
{
    public class HomeViewModel
    {
        public Variant? Variant { get; set; }

        public List<Variant> Variants { get; set; }
    }
}

tim_urfu-teploobmenweb-587e0fcfbe11/TeploobmenWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Diagnostics;
using TeploobmenLibrary;
using TeploobmenWeb.Data;
using TeploobmenWeb.Models;

namespace TeploobmenWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly ApplicationContext _context;

        private int _userId;

        public HomeController(ILogger<HomeController> logger, ApplicationContext applicationContext)
        {
            _logger = logger;
            _context = applicationContext;
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            int.TryParse(User.FindFirst("Id")?.Value, out _userId);
        }

        [HttpPost]
        public IActionResult Result(TeploobmenInput input)
        {
            // Сохранение варианта исходных данных
            if (!string.IsNullOrEmpty(input.Name))
            {
                var existVariant = _context.Variants.FirstOrDefault(x => x.Name == input.Name);

                if (existVariant != null)
                {
                    existVariant.InitTempMat = input.InitTempMat;
                    existVariant.InitTempGas = input.InitTempGas;
                    existVariant.GasSpeed = input.GasSpeed;
                    existVariant.AvgHeatGas = input.AvgHeatGas;
                    existVariant.MatConsumption = input.MatConsumption;
                    existVariant.HeatMat = input.HeatMat;
                    existVariant.HeatCoeff = input.HeatCoeff;
                    existVariant.Diameter = input.Diameter; 

                    _context.Variants.Update(existVariant);
                    _context.SaveChanges();
                }
                else
                {
                    var variant = new Variant
                    {
                        Name = input.Name,
                        InitTempMat = input.InitTempMat,
                        InitTempGas = input.InitTempGas,
                        GasSpeed = input.GasSpeed,
                        AvgHeatGas = input.AvgHeatGas,
                        MatConsumption = input.MatConsumption,
                        HeatMat = input.HeatMat,
                        HeatCoeff = input.HeatCoeff,
                        Diameter = input.Diameter, 
                        UserId = _userId,
                        CreatedAt = DateTime.Now
                    };

                    _context.Variants.Add(variant);
                    _context.SaveChanges();
                }               
            }

            // Выполнение расчета
            var lib = new TeploobmenSolver(input);
            var result = lib.Solve();

            return View(result);
        }

        [HttpGet]
        public IActionResult Index(int? variantId)
        {
            var viewModel = new HomeViewModel();

            if (variantId != null)
            {
                viewModel.Variant = _context.Variants
                    .Where(x => x.UserId == _userId || x.UserId == 0)
                    .FirstOrDefault(x => x.Id == variantId);
            }

            viewModel.Variants = _context.Variants
                .Where(x => x.UserId == _userId || x.UserId == 0)
                .ToList();

            return View(viewModel);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Remove(int? variantId)
        {
            var variant = _context.Variants
                .Where(x => x.UserId == _userId || x.UserId == 0)
                .FirstOrDefault(x => x.Id == variantId);

            if (variant != null)
            {
                _context.Variants.Remove(variant);
                _context.SaveChanges();

                TempData["message"] = $"Вариант {variant.Name} удален.";
            }
            else
            {
                TempData["message"] = $"Вариант не найден.";
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

tim_urfu-teploobmenweb-587e0fcfbe11/TeploobmenWeb/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
using System.Security.Claims;
using TeploobmenLibrary;
using TeploobmenWeb.Data;
using TeploobmenWeb.Models;

namespace TeploobmenWeb.Controllers
{
    public class LoginController : Controller
    {
        private readonly ILogger<LoginController> _logger;

        private readonly ApplicationContext _context;

        public LoginController(ILogger<LoginController> logger, ApplicationContext applicationContext)
        {
            _logger = logger;
            _context = applicationContext;
        }

        [HttpPost]
        public async Task<IActionResult> Index(string email, string password)
        {
            var user = _context.Users.FirstOrDefault(x => x.Email == email && x.Password == password);

            if(user != null)
            {
                var claims = new List<Claim> {
                    new Claim("Id", user.Id.ToString()),
                    new Claim(ClaimTypes.Name, user.Email),
                    new Claim(ClaimTypes.Role, "user"),
                };

                ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, "Cookies");

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult CreateDefaultUser()
        {
            var user = new User { Email = "admin@mail.ru", Password = "12345", Name = "Admin" };
            _context.Users.Add(user);
            _context.SaveChanges();

            return Ok();
        }
    }
}

tim_urfu-teploobmenweb-587e0fcfbe11/TeploobmenWeb/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace TeploobmenWeb.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

tim_urfu-teploobmenweb-587e0fcfbe11/TeploobmenWeb/Views/Home/Index.cshtml
@model HomeViewModel
@{
    ViewData["Title"] = "Расчет теплообмена в стационарном теплообмене в противоточном движении кусковых материалов и газов в плотном продуваемом слое";
}

@if (!string.IsNullOrEmpty(TempData["message"]?.ToString()))
{
    <div class="alert alert-danger">
        @TempData["message"]
    </div>
}


<form action="/Home/Result" method="post">
    <p>
        Начальная температура материала, 0С:<br>
    <input name="InitTempMat" value="@Model.Variant?.InitTempMat" autocomplete="off"  />
    </p>
    <p>
        Начальная температура газа, 0С:<br>
        <input name="InitTempGas" value="@Model.Variant?.InitTempGas" autocomplete="off" />
    </p>
    <p>
        Скорость газа на свободное сечение шахты, м/с:<br>
        <input name="GasSpeed" value="@Model.Variant?.GasSpeed" autocomplete="off" />
    </p>
    <p>
        Средняя теплоемкость газа,кДж: <br>
    <input name="AvgHeatGas" value="@Model.Variant?.AvgHeatGas" autocomplete="off" />
    </p>
    <p>
        Расход материалов, кг/с:<br>
        <input name="MatConsumption" value="@Model.Variant?.MatConsumption" autocomplete="off" />
    </p>
    <p>
        Теплоемкость материалов, кДж:<br>
    <input name="HeatMat" value="@Model.Variant?.HeatMat" autocomplete="off" />
    </p>
    <p>
        Объемный коэффициент теплоотдачи, Вт:<br>
        <input name="HeatCoeff" value="@Model.Variant?.HeatCoeff" autocomplete="off" />
    </p>
    <p>
        Диаметр аппарата, м:<br>
        <input name="Diameter" value="@Model.Variant?.Diameter" autocomplete="off" />
    </p>
    <p>
        Имя:<br>
    <input name="Name" value="@Model.Variant?.Name" autocomplete="off" />
    </p>

    <button type="submit">Рассчитать</button>
</form>

<h2>Варианты расчетов</h2>
<table class="table table-border">
    <tr>
        <td class="vertical-rl">Название варианта</td>
        <td class="vertical-rl">Начальная температура материала, 0С</td>
        <td class="vertical-rl">Начальная температура газа, 0С</td>
        <td class="vertical-rl">Скорость газа на свободное сечение шахты, м/с</td>
        <td class="vertical-rl">Средняя теплоемкость газа,кДж</td>
        <td class="vertical-rl">Расход материалов, кг/с</td>
        <td class="vertical-rl">Теплоемкость материалов, кДж</td>
        <td class="vertical-rl">Объемный коэффициент теплоотдачи, Вт</td>
        <td class="vertical-rl">Диаметр аппарата, м</td>
        <td></td>
    </tr>

    @foreach (var variant in Model.Variants)
    {
        <tr>
            <td>@variant.Name</td>
            <td>@variant.InitTempMat</td>
            <td>@variant.InitTempGas</td>
            <td>@variant.GasSpeed</td>
            <td>@variant.AvgHeatGas</td>
            <td>@variant.MatConsumption</td>
            <td>@variant.HeatMat</td>
            <td>@variant.HeatCoeff</td>
            <td>@variant.Diameter</td>
            <td>
                <a href="/Home/Index/?variantId=@variant.Id">Открыть</a>
                 <a href="/Home/Remove/?variantId=@variant.Id">Удалить</a>
            </td>
        </tr>

    }
</table>

tim_urfu-teploobmenweb-587e0fcfbe11/TeploobmenWeb/Views/Home/Result.cshtml
@model TeploobmenOutput
@{
    ViewData["Title"] = "Home Page";
}

<form method="post">
    <p>
        Начальная температура материала, 0С:<br>
        <input name="InitTempMat" />
    </p>
    <p>
        Начальная температура газа, 0С:<br>
        <input name="InitTempGas"  />
    </p>
    <p>
        Скорость газа на свободное сечение шахты, м/с:<br>
        <input name="GasSpeed" />
    </p>
    <p>
        Средняя теплоемкость газа,кДж:<br>
        <input name="AvgHeatGas"/>
    </p>
    <p>
        Теплоемкость материалов, кДж:<br>
        <input name="MatConsumption" />
    </p>
    <p>
        Расход материалов, кг/с:<br>
        <input name="HeatMat" />
    </p>
    <p>
        Объемный коэффициент теплоотдачи, Вт:<br>
        <input name="HeatCoeff"/>
    </p>
    <p>
        Диаметр аппарата, м:<br> 
        <input name="Diameter"/>
    </p>
    <button type="submit">Рассчитать</button>
</form>

@if(Model != null)
{
    <table class="table">
        <tr>
            <td>Y</td>
            @for (int i = 0; i < Model.Rows.Count; i++)
            {
                <td>@Model.Rows[i].Y</td>
            }
        </tr>
        <tr>
            <td>RelHeight</td>
            @for (int i = 0; i < Model.Rows.Count; i++)
            {
                <td>@Model.Rows[i].RelHeight</td>
            }
        </tr>
        <tr>
            <td>Intermediate1</td>
            @for (int i = 0; i < Model.Rows.Count; i++)
            {
                <td>@Model.Rows[i].Intermediate1</td>
            }
        </tr>
        <tr>
            <td>Intermediate2</td>
            @for (int i = 0; i < Model.Rows.Count; i++)
            {
                <td>@Model.Rows[i].Intermediate2</td>
            }
        </tr>
        <tr>
            <td>V</td>
            @for (int i = 0; i < Model.Rows.Count; i++)
            {
                <td>@Model.Rows[i].V</td>
            }
        </tr>
        <tr>
            <td>RelTempGas</td>
            @for (int i = 0; i < Model.Rows.Count; i++)
            {
                <td>@Model.Rows[i].RelTempGas</td>
            }
        </tr>
        <tr>
            <td>temp</td>
            @for (int i = 0; i < Model.Rows.Count; i++)
            {
                <td>@Model.Rows[i].temp</td>
            }
        </tr>
        <tr>
            <td>Temp</td>
            @for (int i = 0; i < Model.Rows.Count; i++)
            {
                <td>@Model.Rows[i].Temp</td>
            }
        </tr>
        <tr>
            <td>Diff</td>
            @for (int i = 0; i < Model.Rows.Count; i++)
            {
                <td>@Model.Rows[i].Diff</td>
            }
        </tr>
    </table>

    <div>
        <h3>Изменение температуры окатышей и газа по высоте слоя</h3>
        <canvas id="ChartChangeTemp"></canvas>
        <h3>Разность температур окатышей и газа</h3>
        <canvas id="ChartDiffTemp"></canvas>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        const ctx1 = document.getElementById('ChartChangeTemp');
        const data = {
            labels: @Json.Serialize(Model.Rows.Select(x => x.Y).ToList()),
            datasets: [
                {
                    label: 't',
                    data: @Json.Serialize(Model.Rows.Select(x => x.temp).ToList()),

                },
                {
                    label: 'T',
                    data: @Json.Serialize(Model.Rows.Select(x => x.Temp).ToList()),

                }
            ]
        };
        const configLine1 = {
            type: 'line',
            data: data,
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: true,
                    }
                }
            },
        };
        new Chart(ctx1, configLine1);
        const ctx2 = document.getElementById('ChartDiffTemp');
        const data2 = {
            labels: @Json.Serialize(Model.Rows.Select(x => x.Y).ToList()),
            datasets: [
                {
                    label: 'temp',
                    data: @Json.Serialize(Model.Rows.Select(x => x.Diff).ToList()),

                },
            ]
        };
        const configLine2 = {
            type: 'line',
            data: data2,
            options: {
                responsive: true,
                plugins: {
                    legend: {
                        position: 'top',
                    },
                    title: {
                        display: true,
                    }
                }
            },
        };
        new Chart(ctx2, configLine2)
    </script>
    
}

tim_urfu-teploobmenweb-587e0fcfbe11/TeploobmenWeb/Views/Login/Index.cshtml
@model HomeViewModel
@{
    ViewData["Title"] = "Home Page";
}

<form action="/Login/" method="post">
    E-mail:
    <input name="Email" value="" autocomplete="off" />

    Пароль:
    <input name="Password" value="" autocomplete="off" />

    <button type="submit">Войти</button>
</form>

tim_urfu-teploobmenweb-587e0fcfbe11/TeploobmenWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TeploobmenWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TeploobmenWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TeploobmenWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if(User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Выход</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login">Авторизация</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TeploobmenWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

tim_urfu-teploobmenweb-587e0fcfbe11/TeploobmenWeb/Views/User/Index.cshtml
@model HomeViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div>Привет, @User.Identity.Name!</div>